//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinaryClinicManagment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animal()
        {
            this.Consultation = new HashSet<Consultation>();
            this.Passe = new HashSet<Passe>();
            this.Remarques = new HashSet<Remarques>();
            this.SuiviPoids = new HashSet<SuiviPoids>();
        }
    
        public int IdAnimal { get; set; }
        [Required]
        [Display(Name = "Nom")]
        [StringLength(25, ErrorMessage ="Le nom doit être inférieur à 25 caractères.")]
        public string nom { get; set; }
        [Required]
        [Display(Name = "Sexe")]
        public string sexe { get; set; }
        [Display(Name = "Commentaires")]
        public string commentaire { get; set; }
        [Display(Name = "Date de naissance")]
        public Nullable<System.DateTime> dateNaissance { get; set; }
        [Display(Name = "Client lié")]
        public int IdUtilisateur { get; set; }
        [Display(Name = "Espèce et race")]
        public int idEspece { get; set; }

        public virtual Espece Espece { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consultation> Consultation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passe> Passe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remarques> Remarques { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuiviPoids> SuiviPoids { get; set; }
    }
}
