//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinaryClinicManagment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Consultation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consultation()
        {
            this.PrescConsultation = new HashSet<PrescConsultation>();
        }

        [Display(Name = "Numéro de la consultation")]
        public int idObservation { get; set; }
        [Display(Name = "Description du motif")]
        public string description { get; set; }
        [Display(Name = "Date de la consultation")]
        public Nullable<System.DateTime> dateObs { get; set; }
        [Required]
        [Display(Name = "Animal consulté")]
        public int IdAnimal { get; set; }
        [Required]
        [Display(Name = "Vétérinaire en charge")]
        public int IdUtilisateur { get; set; }
        [Display(Name = "Examen clinique")]
        public string examenClinique { get; set; }
        [Display(Name = "Diagnostic")]
        public string diagnostic { get; set; }

        public virtual Animal Animal { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescConsultation> PrescConsultation { get; set; }
    }
}
