//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinaryClinicManagment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Espece
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Espece()
        {
            this.Animal = new HashSet<Animal>();
        }
    
        public int idEspece { get; set; }
        [Required]
        [Display(Name = "Espèce")]
        [StringLength(25, ErrorMessage ="L'espèce doit être inférieure à 25 caractères.")]
        public string espece { get; set; }
        [Required]
        [Display(Name = "Race")]
        [StringLength(25, ErrorMessage = "La race doit être inférieure à 25 caractères.")]
        public string race { get; set; }
        [Display(Name ="Espèce, race")]
        public string esprace { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal> Animal { get; set; }
    }
}
