//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinaryClinicManagment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PrescConsultation
    {
        [Display(Name ="Posologie")]
        [StringLength(25, ErrorMessage = "La posologie doit être inférieure à 25 caractères.")]
        public string posologie { get; set; }
        [Required]
        [Display(Name ="Consultation")]
        public int idObservation { get; set; }
        [Required]
        [Display(Name ="Médicament")]
        public int idMedicament { get; set; }
    
        public virtual Consultation Consultation { get; set; }
        public virtual Medicament Medicament { get; set; }
    }
}
