//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinaryClinicManagment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SuiviPoids
    {
        public int idSuivi { get; set; }
        [Display(Name ="Date du suivi")]
        public Nullable<System.DateTime> dateSuivi { get; set; }
        [Display(Name ="Poids")]
        public Nullable<double> poids { get; set; }
        [Display(Name ="Animal associé")]
        public int IdAnimal { get; set; }
    
        public virtual Animal Animal { get; set; }
    }
}
