//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinaryClinicManagment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Utilisateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilisateur()
        {
            this.Animal = new HashSet<Animal>();
            this.Consultation = new HashSet<Consultation>();
            this.Passe = new HashSet<Passe>();
        }
    
        public int IdUtilisateur { get; set; }
        [Display(Name = "Mot de passe")]
        public string password { get; set; }
        [Required]
        [Display(Name = "Nom")]
        public string nom { get; set; }
        [Required]
        [Display(Name = "Prénom")]
        public string prenom { get; set; }
        [Display(Name = "Téléphone")]
        public string tel { get; set; }
        [Required]
        [Display(Name = "Adresse email")]
        public string mail { get; set; }
        [Display(Name = "Adresse")]
        public string adresse { get; set; }
        [Display(Name = "Ville")]
        public string ville { get; set; }
        [Display(Name = "Code postal")]
        public Nullable<int> codePostal { get; set; }
        public bool estVeto { get; set; }
        public string salt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal> Animal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consultation> Consultation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passe> Passe { get; set; }
    }
}
