//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinaryClinicManagment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VeterinaryClinicEntities : DbContext
    {
        public VeterinaryClinicEntities()
            : base("name=VeterinaryClinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animal> Animal { get; set; }
        public virtual DbSet<Consultation> Consultation { get; set; }
        public virtual DbSet<Espece> Espece { get; set; }
        public virtual DbSet<Medicament> Medicament { get; set; }
        public virtual DbSet<Operation> Operation { get; set; }
        public virtual DbSet<Passe> Passe { get; set; }
        public virtual DbSet<PrescConsultation> PrescConsultation { get; set; }
        public virtual DbSet<Remarques> Remarques { get; set; }
        public virtual DbSet<SuiviPoids> SuiviPoids { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
    }
}
